window.MATERIALS = [
  {
    id: "amethyst",
    name: "Amethyst",
    tone: "purple",
    heroImage: "assets/materials/amethyst-rough-hero.jpg",
    summary: "A core purple quartz material for jewellery, crystal gifts and decor lines.",
    forms: [
      { name: "Cluster", image: "assets/materials/amethyst-cluster.jpg" },
      { name: "Tower", image: "assets/materials/amethyst-tower.jpg" },
      { name: "Tumbled Stones", image: "assets/materials/amethyst-tumbled-stones.jpg" },
      { name: "Beads", image: "assets/materials/amethyst-beads.jpg" },
      { name: "Pendant", image: "assets/materials/amethyst-pendant.jpg" },
    ],
  },
  {
    id: "rose-quartz",
    name: "Rose Quartz",
    tone: "rose",
    heroImage: "assets/materials/rose-quartz-rough-hero.jpg",
    summary: "Soft pink material with broad demand for handmade jewellery and gift products.",
    forms: [
      { name: "Heart", image: "assets/materials/rose-quartz-heart.jpg" },
      { name: "Tower", image: "assets/materials/rose-quartz-tower.jpg" },
      { name: "Tumbled Stones", image: "assets/materials/rose-quartz-tumbled-stones.jpg" },
      { name: "Beads", image: "assets/materials/rose-quartz-beads.jpg" },
      { name: "Thumb Stone", image: "assets/materials/rose-quartz-palm-stone.jpg" },
    ],
  },
  {
    id: "clear-quartz",
    name: "Clear Quartz",
    tone: "clear",
    heroImage: "assets/materials/clear-quartz-rough-hero.jpg",
    summary: "Neutral clear quartz options for bead, pendant, chip and display assortments.",
    forms: [
      { name: "Points", image: "assets/materials/clear-quartz-points.jpg" },
      { name: "Sphere", image: "assets/materials/clear-quartz-sphere.jpg" },
      { name: "Tower", image: "assets/materials/clear-quartz-tower.jpg" },
      { name: "Chips", image: "assets/materials/clear-quartz-chips.jpg" },
      { name: "Pendant", image: "assets/materials/clear-quartz-pendant.jpg" },
    ],
  },
  {
    id: "labradorite",
    name: "Labradorite",
    tone: "blue",
    heroImage: "assets/materials/labradorite-rough-hero.jpg",
    summary: "Flashy feldspar material suited to cabochons, pendants and statement pieces.",
    forms: [
      { name: "Palm Stone", image: "assets/materials/labradorite-palm-stone.jpg" },
      { name: "Cabochons", image: "assets/materials/labradorite-cabochons.jpg" },
      { name: "Beads", image: "assets/materials/labradorite-beads.jpg" },
      { name: "Freeform", image: "assets/materials/labradorite-freeform.jpg" },
      { name: "Pendant", image: "assets/materials/labradorite-pendant.jpg" },
    ],
  },
  {
    id: "lapis-lazuli",
    name: "Lapis Lazuli",
    tone: "lapis",
    heroImage: "assets/materials/lapis-lazuli-rough-hero.jpg",
    summary: "Deep blue material for premium bead strands, cabochons and finished components.",
    forms: [
      { name: "Round Beads", image: "assets/materials/lapis-lazuli-round-beads.jpg" },
      { name: "Rondelle Beads", image: "assets/materials/lapis-lazuli-rondelle-beads.jpg" },
      { name: "Cabochons", image: "assets/materials/lapis-lazuli-cabochons.jpg" },
      { name: "Bracelet", image: "assets/materials/lapis-lazuli-bracelet.jpg" },
      { name: "Pendant", image: "assets/materials/lapis-lazuli-pendant.jpg" },
    ],
  },
  {
    id: "tiger-eye",
    name: "Tiger Eye",
    tone: "gold",
    heroImage: "assets/materials/tiger-eye-rough-hero.jpg",
    summary: "Golden-brown chatoyant stone for bracelet, bead and pendant wholesale ranges.",
    forms: [
      { name: "Round Beads", image: "assets/materials/tiger-eye-round-beads.jpg" },
      { name: "Rondelle Beads", image: "assets/materials/tiger-eye-rondelle-beads.jpg" },
      { name: "Tumbled Stones", image: "assets/materials/tiger-eye-tumbled-stones.jpg" },
      { name: "Bracelet", image: "assets/materials/tiger-eye-bracelet.jpg" },
      { name: "Pendant", image: "assets/materials/tiger-eye-pendant.jpg" },
    ],
  },
  {
    id: "agate",
    name: "Agate",
    tone: "agate",
    heroImage: "assets/materials/agate-rough-hero.jpg",
    summary: "Pattern-rich agate materials for slices, beads, coasters and decor components.",
    forms: [
      { name: "Slices", image: "assets/materials/agate-slices.jpg" },
      { name: "Tower", image: "assets/materials/agate-tower.jpg" },
      { name: "Tumbled Stones", image: "assets/materials/agate-tumbled-stones.jpg" },
      { name: "Beads", image: "assets/materials/agate-beads.jpg" },
      { name: "Coaster Set", image: "assets/materials/agate-coaster-set.jpg" },
    ],
  },
  {
    id: "fluorite",
    name: "Fluorite",
    tone: "green",
    heroImage: "assets/materials/fluorite-rough-hero.jpg",
    summary: "Color-banded fluorite materials for carved pieces, towers and mixed crystal assortments.",
    forms: [
      { name: "Tower", image: "assets/materials/fluorite-tower.jpg" },
      { name: "Sphere", image: "assets/materials/fluorite-sphere.jpg" },
      { name: "Raw Chunks", image: "assets/materials/fluorite-raw-chunks.jpg" },
      { name: "Tumbled Stones", image: "assets/materials/fluorite-tumbled-stones.jpg" },
      { name: "Carving", image: "assets/materials/fluorite-carving.jpg" },
    ],
  },
  {
    id: "citrine",
    name: "Citrine",
    tone: "citrine",
    heroImage: "assets/materials/citrine-rough-hero.jpg",
    summary: "Warm yellow quartz material for bright jewellery, decor and gift assortments.",
    forms: [
      { name: "Tower", image: "assets/materials/citrine-tower.jpg" },
      { name: "Tumbled Stones", image: "assets/materials/citrine-tumbled-stones.jpg" },
      { name: "Beads", image: "assets/materials/citrine-beads.jpg" },
      { name: "Cluster", image: "assets/materials/citrine-cluster.jpg" },
      { name: "Pendant", image: "assets/materials/citrine-pendant.jpg" },
    ],
  },
];
